### ISSUE TITLE
Incorrect Supabase Table Definition in readme.md

### ISSUE THREAD

**Issue by SevanBadal** [SevanBadal/box#7]
The table for messages should be:

Message

- receiver :: Text (foreign key relation: receiver -> channel.name)
- sender :: Text (foreign key relation: sender -> channel.name)
- content :: Text

**Comment by vietthom** [comment]
Just made a push to main with the table updates but got rejected by branch protection.

**Comment by SevanBadal** [comment]
Main is protected. We are roughly following a [trunk-based development](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development) vc management practice. Check out a feature branch `<username>/<feature-description>` and open a PR from the feature branch!

**Comment by SevanBadal** [comment]
fixed in [124a734](https://github.com/SevanBadal/box/commit/124a7344116fdb425d49832afc56ee09fb56b668)
